# Local development configuration for moq-relay.
# Matches the upstream dev profile but lives alongside this project
# so scripts/dev.sh can reference it without depending on the rs tree.

[log]
level = "debug"

[server]
listen = "127.0.0.1:4443"

tls.generate = ["localhost"]

[web.http]
listen = "127.0.0.1:4443"

[auth]
public = ""
